### ISSUE TITLE
Resolving schemas but allow custom fixture data

### ISSUE THREAD

**Issue by phated** [phated/pg-barnum#2]
In many cases, you will need to override the default data generated by your schema with something static.  How should this be handled?  I was thinking everything would be abstracted into a `populate(options, cb)` API but I don't know how to support this with that API.

**Comment by FotoVerite** [comment]
Misunderstood, I think we need to have a third method to override individual factories, sometimes you just want to generate one after another with a generator sometimes you want to override one attribute.
